services:
  dhcpd:
    image: dafydd2277/dhcpd:latest
    environment:
      DHCPD_PROTOCOL: ${i_dhcp_protocol}
    logging:
      driver: syslog
      options:
        tag: cnt-{{.Name}}
        syslog-address: ${s_syslog_connection_type}://${s_syslog_ip}:${i_syslog_port}
        syslog-facility: daemon
    network_mode: host
    volumes:
      - type: bind
        source: ${d_dhcpd_config}
        target: /data
    working_dir: /data

